# Generated by Django 2.2.5 on 2019-09-28 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('order_by', models.CharField(default='Keg', max_length=20)),
                ('quantity_per_order', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)])),
                ('measure', models.CharField(choices=[('unit', 'unit'), ('millilitre', 'millilitre')], default='millilitre', max_length=10)),
                ('amount_per_unit', models.DecimalField(decimal_places=2, default=1.0, max_digits=9, validators=[django.core.validators.MinValueValidator(0)])),
                ('stock_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('disabled', models.BooleanField(default=False)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('discounted_price', models.DecimalField(blank=True, decimal_places=2, default=None, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)])),
                ('sku', models.CharField(blank=True, default='', max_length=50, null=True)),
                ('image', models.CharField(blank=True, default='', max_length=1500)),
                ('tasting_notes', models.CharField(blank=True, default='', max_length=500)),
                ('style', models.CharField(blank=True, default='', max_length=50)),
                ('serving_suggestions', models.CharField(blank=True, default='', max_length=500)),
                ('alcohol_percentage', models.DecimalField(blank=True, decimal_places=3, default=0, max_digits=4, validators=[django.core.validators.MinValueValidator(0)])),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('barcode', models.CharField(blank=True, default='', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'items',
                'ordering': ('name',),
            },
        ),
    ]
