# Generated by Django 2.2.5 on 2019-09-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='supplier',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='supplier.Supplier'),
        ),
        migrations.AlterUniqueTogether(
            name='item',
            unique_together={('supplier', 'sku')},
        ),
    ]
