# Generated by Django 2.2.5 on 2019-09-28 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('licensee_number', models.CharField(blank=True, max_length=300)),
                ('image', models.CharField(blank=True, default='', max_length=150)),
            ],
            options={
                'db_table': 'clients',
            },
        ),
    ]
