# Generated by Django 2.2.5 on 2019-09-28 17:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supplier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('default_payment_term', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('keg_deposit_price', models.DecimalField(decimal_places=2, default=0, max_digits=32, validators=[django.core.validators.MinValueValidator(0)])),
                ('image', models.CharField(blank=True, default='', max_length=150)),
                ('supplier_type', models.CharField(choices=[('brewery', 'brewery'), ('distillery', 'distillery'), ('winery', 'winery')], default='brewery', max_length=150)),
            ],
            options={
                'db_table': 'suppliers',
            },
        ),
    ]
