# Generated by Django 2.2.5 on 2019-09-28 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        ('supplier', '0001_initial'),
        ('item', '0002_auto_20190928_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='supplier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='supplier.Supplier'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='item.Item'),
        ),
        migrations.AddField(
            model_name='lineitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='line_items', to='order.Order'),
        ),
        migrations.AlterUniqueTogether(
            name='lineitem',
            unique_together={('item', 'order')},
        ),
    ]
