# Generated by Django 2.2.5 on 2019-09-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_auto_20190928_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderactivity',
            name='client_seen',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderactivity',
            name='supplier_seen',
            field=models.BooleanField(default=False),
        ),
    ]
