# Generated by Django 2.2.5 on 2019-10-01 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('order', '0003_auto_20190930_1627'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderactivity',
            name='client',
        ),
        migrations.AddField(
            model_name='orderactivity',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='order_activities', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
